.286
ASSUME	CS:CGR,DS:CGR
CGR	GROUP	COD,DAT
COD	SEGMENT BYTE
ORG	100H
TRY	PROC
	MOV	SP,100H
	LEA	SI,FN
	LEA	DX,BUF
	DEC	AX
	CALL	LOAD_FILE
	JC	TRYE
	OR	CL,CL
	JNZ	TRYE
	MOV	DS:[SPRTBL+02H],CS
	MOV	BYTE PTR DS:[SPRTBL+4],CH
	PUSH	CX
	MOV	AX,010H
	INT	10H
	LEA	SI,BUF
	POP	AX
	MOV	AL,'A'
	LEA	DI,SPR_
	MOV	DX,4
	MOV	BX,WORD PTR [INK]
	CALL	SYM2SPR
	LEA	BX,SPRTBL
	MOV	AX,DS:[BX+4]
	MOV	CS:[W],AX
	MOV	AX,DS:[BX+6]
	MOV	CS:[W+2],AX
	MOV	AX,DS:[BX+8]
	MOV	CS:[W+4],AX
	MOV	AX,DS:[BX+0AH]
	MOV	CS:[W+6],AX
	MOV	AL,BYTE PTR CS:[VTBL+8]
	MOV	BYTE PTR CS:[W+8],AL
	CALL	EGAWSPR
	MOV	AH,7
	INT	21H
	LEA	BX,W
	CALL	INVWIN

	MOV	AH,07
	INT	21H
	MOV	AX,3
	INT	10H
	MOV	AX,4C00H
	INT	21H
TRYE:
	MOV	AX,4C01H
	INT	21H
INCLUDE IO.LIB
INCLUDE EGAWSPR.LIB
INCLUDE INVWIN.LIB
INCLUDE BWIN2CRD.LIB
INCLUDE BCRD2COL.LIB
INCLUDE BCOL2WIN.LIB
INCLUDE SYM2SPR.LIB
ENDP

ENDS
DAT	SEGMENT BYTE
FN	DB	'TRY.FNT',0
VIEW_	DB	'PAVEL SKRYLEV''S COMPUTER',0
INCLUDE VIDEO.TBL
SPRTBL	DW	COD:SPR_,0
	DW	0
	DW	8
	DW	128,8
	DB	0
	DB	0,0,0
W	DW	0,0,0,0
	DB	0
	DB	0,0,0,0,0,0,0

INK	DB	15
PAPER	DB	0
SPR_	DB	(8*16)/2	  DUP	      (0)
BUF:
ENDS
END     TRY

